--- #YAML:1.0
name:               Unicode-Transform
version:            0.51
abstract:           conversion among Unicode Transformation Formats
author:
    - SADAHIRO Tomoyuki <SADAHIRO@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DynaLoader:  0
    Exporter:    0
    strict:      0
    warnings:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
